name: Export slides

on:
  push:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Install Marp CLI
      run: npm install -g @marp-team/marp-cli
    - name: Build pdfs
      run: |
        mkdir pdfs
        find ./slides -name "*.md" -exec sh -c 'echo "marp {} -o ./pdfs/{.}.pdf"' \;
        zip -r pdf.zip pdfs
    - name: Build pptxs
      run: |
        mkdir pptxs
        find ./slides -name "*.md" -exec sh -c 'echo "marp {} -o ./pptxs/{.}.pptx"' \;
        zip -r pptx.zip pptxs
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: pdf.zip
    - name: Upload pptx artifact
      uses: actions/upload-artifact@v4
      with:
        name: pptx
        path: pptx.zip
