name: Export slides

on:
  push:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install Marp CLI
      run: npm install -g @marp-team/marp-cli
    - name: Get font
      run: |
        sudo apt-get update
        sudo apt-get install wget unzip
        wget https://github.com/subframe7536/maple-font/releases/download/v7.8/MapleMono-NF-unhinted.zip
        unzip -d font MapleMono-NF-unhinted.zip
        sudo find font -name "*.ttf" -exec cp {} /usr/local/share/fonts/ \;

    - name: Build pdfs
      run: |
        mkdir pdfs
        find ./slides -name "*.md" -exec sh -c 'marp {} -o ./pdfs/$(basename {} .md).pdf' \;
    - name: Build pptxs
      run: |
        mkdir pptxs
        find ./slides -name "*.md" -exec sh -c 'marp {} -o ./pptxs/$(basename {} .md).pptx' \;
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf.zip
        path: pdfs
    - name: Upload pptx artifact
      uses: actions/upload-artifact@v4
      with:
        name: pptx.zip
        path: pptxs
