name: Export slides

on:
  push:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install Marp CLI
      run: npm install -g @marp-team/marp-cli
    - name: Build pdfs
      run: |
        mkdir pdfs
        find ./slides -name "*.md" -exec sh -c 'echo "marp {} -o ./pdfs/$(basename {} .md).pdf"' \;
    - name: Build pptxs
      run: |
        mkdir pptxs
        find ./slides -name "*.md" -exec sh -c 'echo "marp {} -o ./pptxs/$(basename {} .md).pptx"' \;
        ls pptxs
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf.zip
        path: pdfs
    - name: Upload pptx artifact
      uses: actions/upload-artifact@v4
      with:
        name: pptx.zip
        path: pptxs
